spring.datasource.url=jdbc:mysql://localhost:3306/ai_ip
spring.datasource.username=root
spring.datasource.password=nk@17211
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true